### ISSUE TITLE
Application pre-instantiates the singletons even though `@ComponentScan(lazyInit = true)` is set

### ISSUE THREAD

**Issue by ugultopu** [danielolszewski/blog#1]
Hi Daniel,

I have followed your [Faster Spring Boot Startup](http://dolszewski.com/spring/faster-spring-boot-startup/) post. After making the suggested changes in the main class, my main class looks like the following:

```java
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Configuration
    @Profile("dev")
    @ComponentScan(lazyInit = true)
    static class LocalConfig {
    }

    // A couple of @Bean definitions

}
```
I run the application with:

`mvn spring-boot:run -Drun.profiles=dev`

After running, I sampled the application with [VisualVM](http://visualvm.github.io/). This is the result:

![screen shot 2017-11-28 at 14 29 33](https://user-images.githubusercontent.com/9937444/33337586-c49b0f98-d449-11e7-9b82-ae817ac0b0e0.png)

Despite the `lazyInit = true`, the application still spends a lot of time on `preInstantiateSingletons`.

Is this expected? I thought that after setting `lazyInit = true`, the application would not pre-instantiate the singletons at all.

What am I missing here?

Best

**Comment by danielolszewski** [comment]
Hi Ugultopu,

If you enable lazy initialization, a bean is created when it is used for the first time. What is more, if such bean depends on other beans, they are also initialized. 

Lazy initialization can postpone creation of some beans to the moment when they are needed, but your assumption that none of them is pre-instantiated is wrong as some beans are used when the application starts.

Did you compare initialization time with `lazyInit`set to true and false? If you don't see any difference, maybe your application's startup depends on too many beans.
